version: '3'
services:
  postgres:
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    container_name: async_chess_db
    environment:
      - POSTGRES_DB=async_chess
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - "8080"
      - "5432"
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"
      - "8080:8080"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: