name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:

  vet:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Go Vet
      run: go vet -v ./...

  build:
    runs-on: ubuntu-latest
    needs: ["vet"]
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
